ALTER ROLE mbyte CREATEDB;
CREATE DATABASE manager;
CREATE DATABASE store;
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE manager TO mbyte;
GRANT ALL PRIVILEGES ON DATABASE store TO mbyte;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO mbyte;
