ALTER ROLE mbyte CREATEDB;
CREATE DATABASE manager;
CREATE DATABASE keycloak;
CREATE DATABASE storedev;
GRANT ALL PRIVILEGES ON DATABASE manager TO mbyte;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO mbyte;
GRANT ALL PRIVILEGES ON DATABASE storedev TO mbyte;
